<?php

namespace Dedoc\Scramble\Tests\Infer\Definition;

use Dedoc\Scramble\Infer\Definition\ClassDefinition;
use Dedoc\Scramble\Infer\Definition\ClassPropertyDefinition;
use Dedoc\Scramble\Infer\Definition\PropertyVisibility;
use Dedoc\Scramble\Support\Type\IntegerType;

it('round-trips a definition through serialization', function () {
    $definition = new ClassPropertyDefinition(
        type: new IntegerType,
        isStatic: true,
        visibility: PropertyVisibility::Private,
    );

    $restored = unserialize(serialize($definition));

    expect($restored->visibility)->toBe(PropertyVisibility::Private)
        ->and($restored->isStatic)->toBeTrue();
});

// The shipped dictionary (dictionaries/classMap.php) is generated by hand via
// dictionaries/scripts/generate.php and committed. If it is generated before a new
// property is added to ClassPropertyDefinition, the serialized blobs miss that
// property and unserializing them at boot makes any later property access throw
// "Typed property ... must not be accessed before initialization". This guards
// against shipping such a stale dictionary.
it('ships a dictionary whose property definitions deserialize completely', function () {
    $classMap = require __DIR__.'/../../../dictionaries/classMap.php';

    expect($classMap)->not->toBeEmpty();

    foreach ($classMap as $className => $serializedClassDefinition) {
        $definition = unserialize($serializedClassDefinition);

        expect($definition)->toBeInstanceOf(ClassDefinition::class);

        foreach ($definition->properties as $name => $property) {
            expect($property)->toBeInstanceOf(ClassPropertyDefinition::class);

            // Accessing every property must not throw "accessed before initialization".
            expect($property->visibility)->toBeInstanceOf(PropertyVisibility::class)
                ->and($property->isStatic)->toBeBool()
                ->and($property->attributes)->toBeArray();
        }
    }
});
